# CRIMES ANALYSIS
En este notebook se va a documentar los procesos necesarios para realizarle un EDA al dataset con el objetivo de adecuar los datos y limpiarlos para crear un modelo mediante machine learning basandose en estos datos.

## ¿DE QUE TRATA EL DATASET?
Este dataset guarda informacion de **757141** casos de crimentes sucedidos en Los Angeles, revelando informacion relevante sobre estos desde **informacion** de la **victima** hasta el contexto del crimen, **que armas** se usaron, **que delito/s** se llevaron a cabo, **donde** sucedio exactamente, etc....

# 1. Importe de librerias

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import mutual_info_score
import kagglehub
from kagglehub import KaggleDatasetAdapter
# Configuración básica
plt.rcParams['figure.figsize'] = (8,5)
print('Librerías cargadas correctamente')

Librerías cargadas correctamente

c:\Users\errec\Documents\Python B1\Runojanh-NadieEscapa\venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

# 2. Carga del Dataset

## URL de dataset:
 * #### https://www.kaggle.com/datasets/venkatsairo4899/los-angeles-crime-data-2020-2023?select=Crime_Data_from_2020_to_Present.csv

In [42]:
#Creacion de subconjuntos
ruta = "..\\data\\Crime_Data_from_2020_to_Present.csv"
# df = pd.read_csv(ruta)
# df_filtrado_no_investigados = df[df['Status Desc'] != 'Invest Cont'].copy()
# df_filtrado_no_investigados.to_csv('..\\data\\Dataset_crimes_not_invest.csv', index=False)
# df_filtrado_investigados = df[df['Status Desc'] == 'Invest Cont'].copy()
# df_filtrado_investigados.to_csv('..\\data\\Dataset_crimes_invest.csv', index=False)

# ruta = "..\\data\\Dataset_crimes_not_invest.csv"
df = pd.read_csv(ruta)
df.head()

,DR_NO,Date Rptd,DATE OCC,TIME OCC,AREA,AREA NAME,Rpt Dist No,Part 1-2,Crm Cd,Crm Cd Desc,...,Status,Status Desc,Crm Cd 1,Crm Cd 2,Crm Cd 3,Crm Cd 4,LOCATION,Cross Street,LAT,LON
0,10304468,01/08/2020 12:00:00 AM,01/08/2020 12:00:00 AM,2230,3,Southwest,377,2,624,BATTERY - SIMPLE ASSAULT,...,AO,Adult Other,624.0,NaN,NaN,NaN,1100 W 39TH PL,NaN,34.0141,-118.2978
1,190101086,01/02/2020 12:00:00 AM,01/01/2020 12:00:00 AM,330,1,Central,163,2,624,BATTERY - SIMPLE ASSAULT,...,IC,Invest Cont,624.0,NaN,NaN,NaN,700 S HILL ST,NaN,34.0459,-118.2545
2,200110444,04/14/2020 12:00:00 AM,02/13/2020 12:00:00 AM,1200,1,Central,155,2,845,SEX OFFENDER REGISTRANT OUT OF COMPLIANCE,...,AA,Adult Arrest,845.0,NaN,NaN,NaN,200 E 6TH ST,NaN,34.0448,-118.2474
3,191501505,01/01/2020 12:00:00 AM,01/01/2020 12:00:00 AM,1730,15,N Hollywood,1543,2,745,VANDALISM - MISDEAMEANOR ($399 OR UNDER),...,IC,Invest Cont,745.0,998.0,NaN,NaN,5400 CORTEEN PL,NaN,34.1685,-118.4019
4,191921269,01/01/2020 12:00:00 AM,01/01/2020 12:00:00 AM,415,19,Mission,1998,2,740,"VANDALISM - FELONY ($400 & OVER, ALL CHURCH VA...",...,IC,Invest Cont,740.0,NaN,NaN,NaN,14400 TITUS ST,NaN,34.2198,-118.4468

# 3. Exploracion Inicial del Dataset

### tamaño de Dataset

In [15]:
df.shape

(151337, 21)

In [3]:
df.columns

Index(['DR_NO', 'Date Rptd', 'DATE OCC', 'TIME OCC', 'AREA', 'AREA NAME',
       'Rpt Dist No', 'Part 1-2', 'Crm Cd', 'Crm Cd Desc', 'Mocodes',
       'Vict Age', 'Vict Sex', 'Vict Descent', 'Premis Cd', 'Premis Desc',
       'Weapon Used Cd', 'Weapon Desc', 'Status', 'Status Desc', 'Crm Cd 1',
       'Crm Cd 2', 'Crm Cd 3', 'Crm Cd 4', 'LOCATION', 'Cross Street', 'LAT',
       'LON'],
      dtype='str')

In [45]:
# AREA	Part 1-2	Vict Age	Vict Sex	Vict Descent	Premis Cd	Weapon Used Cd	Status Desc	Crm Cd 1	Crm Cd 2	Crm Cd 3	Crm Cd 4
df=df[["AREA NAME", "Part 1-2","Vict Age","Vict Sex","Vict Descent","Premis Desc","Weapon Desc", "Status Desc","Crm Cd Desc","Crm Cd 2","Crm Cd 3", "Crm Cd 4", "DATE OCC", "TIME OCC"]]

### informacion del dataset

In [8]:
df.info()

<class 'pandas.DataFrame'>
Index: 151337 entries, 0 to 757119
Data columns (total 12 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   AREA            151337 non-null  int64
 1   Part 1-2        151337 non-null  int64
 2   Vict Age        151337 non-null  int64
 3   Vict Sex        145449 non-null  str
 4   Vict Descent    145446 non-null  str
 5   Premis Cd       151337 non-null  float64
 6   Weapon Used Cd  104087 non-null  float64
 7   Status Desc     151337 non-null  str
 8   Crm Cd 1        151337 non-null  float64
 9   Crm Cd 2        25388 non-null   float64
 10  Crm Cd 3        1290 non-null    float64
 11  Crm Cd 4        38 non-null      float64
dtypes: float64(6), int64(3), str(3)
memory usage: 15.0 MB

### descripcion detallada de Dataset

In [5]:
df.describe()

,DR_NO,TIME OCC,AREA,Rpt Dist No,Part 1-2,Crm Cd,Vict Age,Premis Cd,Weapon Used Cd,Crm Cd 1,Crm Cd 2,Crm Cd 3,Crm Cd 4,LAT,LON
count,7.571410e+05,757141.000000,757141.000000,757141.000000,757141.000000,757141.000000,757141.000000,757132.000000,263079.000000,757131.000000,56016.000000,1872.000000,56.000000,757141.000000,757141.000000
mean,2.148771e+08,1334.814871,10.718368,1118.245674,1.415613,500.847668,29.909412,305.938960,362.590230,500.589136,957.298861,983.676282,990.232143,33.971554,-117.999799
std,1.033130e+07,653.847053,6.092302,609.235556,0.492828,207.952490,21.731307,216.793004,123.737617,207.743554,111.871937,51.356926,28.834317,1.864571,6.465919
min,8.170000e+02,1.000000,1.000000,101.000000,1.000000,110.000000,-2.000000,101.000000,101.000000,110.000000,210.000000,434.000000,821.000000,0.000000,-118.667600
25%,2.021135e+08,900.000000,6.000000,622.000000,1.000000,331.000000,11.000000,101.000000,309.000000,331.000000,998.000000,998.000000,998.000000,34.013300,-118.429500
50%,2.119136e+08,1415.000000,11.000000,1142.000000,1.000000,442.000000,31.000000,203.000000,400.000000,442.000000,998.000000,998.000000,998.000000,34.058400,-118.321400
75%,2.215089e+08,1900.000000,16.000000,1618.000000,2.000000,626.000000,45.000000,501.000000,400.000000,626.000000,998.000000,998.000000,998.000000,34.163100,-118.273900
max,2.399165e+08,2359.000000,21.000000,2199.000000,2.000000,956.000000,120.000000,974.000000,516.000000,956.000000,999.000000,999.000000,999.000000,34.334300,0.000000

# 4.Filtro de datos
Categorias a usar

para identificar cuales van a ser las variables predictorias, lo mas comun es usar una matriz de correlacion la cual solo muestra correlaciones con datos numericos, por lo tanto se va a usar Mutual Information para ver correlaciones para variables no numericas sin necesidad de codificarlas.

# Dividiendo dataset
## 1.Subconjunto ya investigados.
## 2.Subconjunto en investigacion.

In [46]:
#1
df["Status Desc"]=df["Status Desc"].map(
    {
    "Adult Arrest":"arrest",
    "Juv Arrest":"arrest", 
    "Adult Other":"no_arrest", 
    "Juv Other":"no_arrest"
    })
df=df.dropna(subset="Status Desc")

In [ ]:
#2

In [58]:
df.isnull().sum()

AREA NAME       0
Part 1-2        0
Vict Age        0
Vict Sex        0
Vict Descent    0
Premis Desc     0
Weapon Desc     0
Status Desc     0
Crm Cd Desc     0
Crm Cd 2        0
Crm Cd 3        0
Crm Cd 4        0
DATE OCC        0
TIME OCC        0
dtype: int64

In [48]:
df["Vict Sex"]=df["Vict Sex"].fillna("X")

In [51]:
df["Vict Sex"].value_counts()

Vict Sex
F    73038
M    61633
X    16666
Name: count, dtype: int64

In [50]:
df["Vict Sex"]=df["Vict Sex"].replace("H", "X")

In [28]:
df["Vict Descent"].value_counts()

Vict Descent
H    64196
B    27051
W    26989
X    18018
O    11504
A     3012
K      278
F      117
I       39
C       38
J       24
V       16
U       13
P       13
Z       13
G       11
S        3
D        2
Name: count, dtype: int64

In [52]:
df["Vict Descent"]=df["Vict Descent"].fillna("X")

In [53]:
df["Premis Desc"]=df["Premis Desc"].fillna("X")

WEAPON

In [44]:
df["Weapon Desc"].value_counts()

Weapon Desc
STRONG-ARM (HANDS, FIST, FEET OR BODILY FORCE)    141322
UNKNOWN WEAPON/OTHER WEAPON                        27323
VERBAL THREAT                                      19409
HAND GUN                                           16320
SEMI-AUTOMATIC PISTOL                               6006
                                                   ...
MAC-11 SEMIAUTOMATIC ASSAULT WEAPON                    3
MAC-10 SEMIAUTOMATIC ASSAULT WEAPON                    2
M1-1 SEMIAUTOMATIC ASSAULT RIFLE                       1
HECKLER & KOCH 91 SEMIAUTOMATIC ASSAULT RIFLE          1
M-14 SEMIAUTOMATIC ASSAULT RIFLE                       1
Name: count, Length: 79, dtype: int64

In [54]:
df["Weapon Desc"]=df["Weapon Desc"].fillna("UNKNOWN WEAPON/OTHER WEAPON")

In [55]:
df["Crm Cd 2"]=df["Crm Cd 2"].fillna(0)

In [56]:
df["Crm Cd 3"]=df["Crm Cd 3"].fillna(0)

In [57]:
df["Crm Cd 4"]=df["Crm Cd 4"].fillna(0)

## Seleccion Columnas
el dataset contiene las siguientes variables:
* **DR_NO:** int64  
* **Date Rptd:** str    
* **DATE OCC:** str    
* **TIME OCC:** int64  
* **AREA:** int64  
* **AREA NAME:** str    
* **Rpt Dist No:** int64  
* **Part 1-2:** int64  
* **Crm Cd:** int64  
* **Crm Cd Desc:** str    
* **Mocodes:** str    
* **Vict Age:** int64  
* **Vict Sex:** str    
* **Vict Descent:** str    
* **Premis Cd:** float64
* **Premis Desc:** str    
* **Weapon Used Cd:** float64
* **Weapon Desc:** str    
* **Status:** str    
* **Status Desc:** str    
* **Crm Cd 1:** float64
* **Crm Cd 2:** float64
* **Crm Cd 3:** float64
* **Crm Cd 4:** float64
* **LOCATION:** str    
* **Cross Street:** str    
* **LAT:** float64
* **LON:** float64

y se ha decidido que las mas importantes son:
* **DR_NO:** representa info acerca del numero de caso, es decir, es el indice.
* **TIME OCC:** representa info acerca de la hora en formato militar.
* **DATE OCC:** representa info acerca de la fecha del crimen.
* **AREA NAME:** representa info acerca del barrio donde sucedio el crimen.
* **Crm Cd Desc:** representa info acerca de la descripcion del primer delito del caso
* **Crm Cd 2:** representa info acerca del codigo de delito del segundo delito del caso.
* **Crm Cd 3:** representa info acerca del codigo de delito del tercer delito del caso. 
* **Crm Cd 4:** representa info acerca del codigo de delito del cuarto delito del caso.
* **Vict Age:** representa info acerca de la edad de la victima.
* **Vict Sex:** representa info acerca del genero de la victima.
* **Vict Descent:** representa info acerca de la descendencia de la victima, es decir, si el blanco, hispano, asiatico, etc....
* **Premis Desc:** representa info acerca de la ubicacion del crimen mas concretamente en que tipo de ubicacion, por ejemplo: hotel, mini-mart, hospital, street, etc..
* **Weapon Desc:** representa info acerca del tipo de arma usada, por ejemplo: knife, stick, hand gun, strong-arm.
* **Status Desc:** representa info acerca de si el acusado ha sido arrestado o si el caso sigue en investigacion.
* **Part 1-2:** representa info acerca de la gravedad del caso siendo el 2 un delito menos agravante que el 1.
* **LOCATION:** representa info acerca de la direccion de la calle donde sucedio el crimen.

In [60]:
df.to_csv("..\\data\\crimeData_subconjunto.csv")