# CRIMES ANALYSIS
En este notebook se va a documentar los procesos necesarios para realizarle un EDA al dataset con el objetivo de adecuar los datos y limpiarlos para entrenar un modelo mediante machine learning basandose en estos datos.

## ¿DE QUE TRATA EL DATASET?
Este dataset guarda informacion de **757141** casos de crimentes sucedidos en Los Angeles, revelando informacion relevante sobre estos desde **informacion** de la **victima** hasta el contexto del crimen, **que armas** se usaron, **que delito/s** se llevaron a cabo, **donde** sucedio exactamente, etc....

# 1. Importe de librerias

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import mutual_info_score
print('Librerías cargadas correctamente')

Librerías cargadas correctamente

# 2. Carga del Dataset

## URL de dataset:
 * #### https://www.kaggle.com/datasets/venkatsairo4899/los-angeles-crime-data-2020-2023?select=Crime_Data_from_2020_to_Present.csv

In [35]:
#Creacion de subconjuntos
ruta = "..\\data\\Crime_Data_from_2020_to_Present.csv"

df = pd.read_csv(ruta)
df.head()

,DR_NO,Date Rptd,DATE OCC,TIME OCC,AREA,AREA NAME,Rpt Dist No,Part 1-2,Crm Cd,Crm Cd Desc,...,Status,Status Desc,Crm Cd 1,Crm Cd 2,Crm Cd 3,Crm Cd 4,LOCATION,Cross Street,LAT,LON
0,10304468,01/08/2020 12:00:00 AM,01/08/2020 12:00:00 AM,2230,3,Southwest,377,2,624,BATTERY - SIMPLE ASSAULT,...,AO,Adult Other,624.0,NaN,NaN,NaN,1100 W 39TH PL,NaN,34.0141,-118.2978
1,190101086,01/02/2020 12:00:00 AM,01/01/2020 12:00:00 AM,330,1,Central,163,2,624,BATTERY - SIMPLE ASSAULT,...,IC,Invest Cont,624.0,NaN,NaN,NaN,700 S HILL ST,NaN,34.0459,-118.2545
2,200110444,04/14/2020 12:00:00 AM,02/13/2020 12:00:00 AM,1200,1,Central,155,2,845,SEX OFFENDER REGISTRANT OUT OF COMPLIANCE,...,AA,Adult Arrest,845.0,NaN,NaN,NaN,200 E 6TH ST,NaN,34.0448,-118.2474
3,191501505,01/01/2020 12:00:00 AM,01/01/2020 12:00:00 AM,1730,15,N Hollywood,1543,2,745,VANDALISM - MISDEAMEANOR ($399 OR UNDER),...,IC,Invest Cont,745.0,998.0,NaN,NaN,5400 CORTEEN PL,NaN,34.1685,-118.4019
4,191921269,01/01/2020 12:00:00 AM,01/01/2020 12:00:00 AM,415,19,Mission,1998,2,740,"VANDALISM - FELONY ($400 & OVER, ALL CHURCH VA...",...,IC,Invest Cont,740.0,NaN,NaN,NaN,14400 TITUS ST,NaN,34.2198,-118.4468

In [42]:
df["Status Desc"].value_counts()

Status Desc
Adult Other     81519
Adult Arrest    66147
Juv Arrest       2391
Juv Other        1280
Name: count, dtype: int64

# Dividiendo dataset

## Subconjunto en investigacion.

In [39]:
dfinvestigados=df[(df["Status Desc"]=="UNK") | (df["Status Desc"]=="Invest Cont")]
dfinvestigados["Status Desc"].replace(to_replace="UNK", value="Invest Cont")

dfinvestigados.to_csv("..\\data\\crimeData_subconjunto_invest.csv")

In [41]:
df=df[(df["Status Desc"]!="UNK") & (df["Status Desc"]!="Invest Cont")]

# 3. Exploracion Inicial del Dataset

### tamaño de Dataset

In [6]:
df.shape

(151337, 28)

In [7]:
df.columns

Index(['DR_NO', 'Date Rptd', 'DATE OCC', 'TIME OCC', 'AREA', 'AREA NAME',
       'Rpt Dist No', 'Part 1-2', 'Crm Cd', 'Crm Cd Desc', 'Mocodes',
       'Vict Age', 'Vict Sex', 'Vict Descent', 'Premis Cd', 'Premis Desc',
       'Weapon Used Cd', 'Weapon Desc', 'Status', 'Status Desc', 'Crm Cd 1',
       'Crm Cd 2', 'Crm Cd 3', 'Crm Cd 4', 'LOCATION', 'Cross Street', 'LAT',
       'LON'],
      dtype='str')

### informacion del dataset

In [8]:
df.info()

<class 'pandas.DataFrame'>
Index: 151337 entries, 0 to 757119
Data columns (total 28 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   DR_NO           151337 non-null  int64
 1   Date Rptd       151337 non-null  str
 2   DATE OCC        151337 non-null  str
 3   TIME OCC        151337 non-null  int64
 4   AREA            151337 non-null  int64
 5   AREA NAME       151337 non-null  str
 6   Rpt Dist No     151337 non-null  int64
 7   Part 1-2        151337 non-null  int64
 8   Crm Cd          151337 non-null  int64
 9   Crm Cd Desc     151337 non-null  str
 10  Mocodes         144699 non-null  str
 11  Vict Age        151337 non-null  int64
 12  Vict Sex        145449 non-null  str
 13  Vict Descent    145446 non-null  str
 14  Premis Cd       151337 non-null  float64
 15  Premis Desc     151245 non-null  str
 16  Weapon Used Cd  104087 non-null  float64
 17  Weapon Desc     104087 non-null  str
 18  Status          151337 non-null  str
 19  Status Desc     151337 non-null  str
 20  Crm Cd 1        151337 non-null  float64
 21  Crm Cd 2        25388 non-null   float64
 22  Crm Cd 3        1290 non-null    float64
 23  Crm Cd 4        38 non-null      float64
 24  LOCATION        151337 non-null  str
 25  Cross Street    22952 non-null   str
 26  LAT             151337 non-null  float64
 27  LON             151337 non-null  float64
dtypes: float64(8), int64(7), str(13)
memory usage: 33.5 MB

### descripcion detallada de Dataset

In [9]:
df.describe()

,DR_NO,TIME OCC,AREA,Rpt Dist No,Part 1-2,Crm Cd,Vict Age,Premis Cd,Weapon Used Cd,Crm Cd 1,Crm Cd 2,Crm Cd 3,Crm Cd 4,LAT,LON
count,1.513370e+05,151337.000000,151337.000000,151337.000000,151337.000000,151337.000000,151337.000000,151337.000000,104087.000000,151337.000000,25388.000000,1290.000000,38.000000,151337.000000,151337.000000
mean,2.129858e+08,1339.527650,11.039495,1149.898234,1.591957,562.129136,32.437137,353.731077,369.937956,561.497796,961.006617,987.406977,994.842105,34.080355,-118.354954
std,9.889631e+06,655.812164,6.133926,613.596811,0.491473,244.496104,19.562811,204.076308,111.765465,244.188224,101.793598,44.305076,13.704460,0.275581,0.867332
min,1.030447e+07,1.000000,1.000000,101.000000,1.000000,110.000000,-2.000000,101.000000,101.000000,110.000000,210.000000,434.000000,930.000000,0.000000,-118.667300
25%,2.018093e+08,900.000000,6.000000,625.000000,1.000000,310.000000,21.000000,108.000000,400.000000,310.000000,998.000000,998.000000,998.000000,34.016800,-118.442100
50%,2.114144e+08,1415.000000,11.000000,1162.000000,2.000000,624.000000,32.000000,501.000000,400.000000,624.000000,998.000000,998.000000,998.000000,34.066300,-118.327700
75%,2.211083e+08,1900.000000,16.000000,1675.000000,2.000000,740.000000,45.000000,502.000000,400.000000,740.000000,998.000000,998.000000,998.000000,34.186700,-118.278300
max,2.399090e+08,2359.000000,21.000000,2198.000000,2.000000,956.000000,99.000000,973.000000,516.000000,956.000000,999.000000,999.000000,998.000000,34.334300,0.000000

# 4.Limpieza

In [10]:
df.isnull().sum()

DR_NO                  0
Date Rptd              0
DATE OCC               0
TIME OCC               0
AREA                   0
AREA NAME              0
Rpt Dist No            0
Part 1-2               0
Crm Cd                 0
Crm Cd Desc            0
Mocodes             6638
Vict Age               0
Vict Sex            5888
Vict Descent        5891
Premis Cd              0
Premis Desc           92
Weapon Used Cd     47250
Weapon Desc        47250
Status                 0
Status Desc            0
Crm Cd 1               0
Crm Cd 2          125949
Crm Cd 3          150047
Crm Cd 4          151299
LOCATION               0
Cross Street      128385
LAT                    0
LON                    0
dtype: int64

## TRATAMIENTO DE NULOS
Se tratarán los nulos de las siguientes variables:``Mocodes``, ``Vict Sex``, ``Vict Descent``, ``Premis``, ``Weapon``, ``Crm``, ``Cross Street``

* ### Mocodes
Esta variable no aporta ninguna informacion crucial y menos aun para ser una predictiva, por lo tanto, nos desharemos de ella.

In [11]:
df=df.drop("Mocodes", axis=1)

* ### Sexo de la victima
la variable ``Vict Sex`` podria ser una columna feature, debido a que nos proporciona info de la victima.

In [12]:
df["Vict Sex"].value_counts()

Vict Sex
F    73038
M    61633
X    10766
H       12
Name: count, dtype: int64

Se puede ver los 3 tipos de valores con mayor demanda para esta variable, dichos tipos de variables hacen referencia al género masculino ,femenino y al desconocido, es decir, el PDLA(Police Department Los Angeles) ya tiene un carácter reservado para los géneros desconocidos, así es como trataremos los nulos, teniendo en cuenta también los otros tipos de valores los reemplazaremos por esta X

In [13]:
#Rellenamos valores nulos.
df["Vict Sex"]= df["Vict Sex"].fillna("X")

#Reemplazamos esos valores raros con pocas ocurrencias.
df["Vict Sex"]= df["Vict Sex"].replace(to_replace="[^MFX]", value="X", regex=True)

* ### Descendencia/etnia de la victima
la variable ``Vict Descent`` podria ser una columna feature, debido a que nos proporciona info de la victima.

In [14]:
df["Vict Descent"].value_counts()

Vict Descent
H    64196
B    27051
W    26989
X    12127
O    11504
A     3012
K      278
F      117
I       39
C       38
J       24
V       16
U       13
P       13
Z       13
G       11
S        3
D        2
Name: count, dtype: int64

De nuevo volvemos a tener un carácter reservado para aquellas descendencias desconocidas, al igual que hemos hecho para el sexo de la víctima se tratarán los nulos rellenándolos con dicho carácter.

In [15]:
#Rellenamos valores nulos.
df["Vict Descent"]= df["Vict Descent"].fillna("X")

#Reemplazamos esos valores raros con pocas ocurrencias.
df["Vict Descent"]= df["Vict Descent"].replace(to_replace="[-]", value="X", regex=True)

* ### Descripcion del lugar
la variable ``Premis`` podria ser una columna feature, debido a que nos proporciona info del contexto del crimen, en concreto usaremos la variable ``Premis Cd`` que ya nos ahorra el trabajo de codificar una variable categorica.

In [16]:
df=df.drop("Premis Desc", axis=1)

In [17]:
df["Premis Cd"]=df["Premis Cd"].fillna(0)

En este caso los nulos se rellenarán con un cero

* ### Arma Usada
la variable ``Weapon`` podria ser una columna feature, debido a que nos proporciona info del contexto del crimen, en concreto usaremos la variable ``Weapon Used Cd`` que ya nos ahorra el trabajo de codificar una variable categorica.

In [18]:
df["Weapon Desc"].value_counts()

Weapon Desc
STRONG-ARM (HANDS, FIST, FEET OR BODILY FORCE)    60681
VERBAL THREAT                                      8767
UNKNOWN WEAPON/OTHER WEAPON                        7988
HAND GUN                                           4378
KNIFE WITH BLADE 6INCHES OR LESS                   2496
                                                  ...
AUTOMATIC WEAPON/SUB-MACHINE GUN                      4
BLACKJACK                                             2
ANTIQUE FIREARM                                       2
M1-1 SEMIAUTOMATIC ASSAULT RIFLE                      1
HECKLER & KOCH 91 SEMIAUTOMATIC ASSAULT RIFLE         1
Name: count, Length: 75, dtype: int64

Cómo se aprecia en la salida del código anterior podemos ver que hay un tipo de valor para la variable ``Weapon Desc`` que hace referencia a que no hay un arma o se trata de un arma desconocida, primero revelaremos a qué código de arma hace referencia está descripción y rellenaremos con este código todos los nulos de ``Weapon Used Cd`` interpretando así que se trata de casos en los que no se han registrado armas.

In [19]:
codeDesconocido=float(df.loc[
df["Weapon Desc"]=="UNKNOWN WEAPON/OTHER WEAPON", "Weapon Used Cd"
].iloc[0])
df["Weapon Used Cd"]=df["Weapon Used Cd"].fillna(codeDesconocido)

Y finalmente podemos eliminar la variable ``Weapon Desc``

In [20]:
df=df.drop("Weapon Desc", axis=1)

* ### Delitos
La variable ``Crm`` podria ser una columna feature debido a que nos informa del tipo de crimen, dado que se nos proporciona tanto el delito principal(``Crm Cd Desc``, ``Crm Cd`` y ``Crm Cd 1``) como los delitos secundarios(``Crm Cd 2``, ``Crm Cd 3``,``Crm Cd 4``) para el primer caso usaremos la variable ``Crm Cd`` que ya nos ahorra el trabajo de codificar una variable categorica 
> para el delito principal a pesar de que tenemos otra variable que nos da la misma informacion ``Crm Cd 1`` se ha elegido la que no tiene nulos.

para los casos secundarios se usaran los tres que aportan informacion de los delitos adicionales: ``Crm Cd 2``, ``Crm Cd 3``,``Crm Cd 4``

Por lo tanto se eliminarán dichas variables que aportan información duplicada o no codificada.

In [21]:
df=df.drop(columns=["Crm Cd Desc", "Crm Cd 1"])

Al igual que en el caso de la descripción del lugar(``Premis Cd``) se rellenarán los nulos con un código **0** interpretando así que no ha habido crímenes secundarios.

In [22]:
df["Crm Cd 2"]=df["Crm Cd 2"].fillna(0)
df["Crm Cd 3"]=df["Crm Cd 3"].fillna(0)
df["Crm Cd 4"]=df["Crm Cd 4"].fillna(0)

* ### Calle transversal
la variable ``Cross Street`` según el departamento de policía de Los Ángeles(LAPD) busca dar una información más precisa acerca de la localización, es decir, además de la dirección de la calle(``Location``) también se da la calle que intersecta con ella, en nuestro caso ya tenemos suficiente con la información de la principal, por lo tanto dicha variable es irrelevante para el entrenado del modelo.

In [23]:
df=df.drop("Cross Street", axis=1)

> Y finalmente asi es como se nos queda la tabla de nulos:

In [24]:
df.isnull().sum()

DR_NO             0
Date Rptd         0
DATE OCC          0
TIME OCC          0
AREA              0
AREA NAME         0
Rpt Dist No       0
Part 1-2          0
Crm Cd            0
Vict Age          0
Vict Sex          0
Vict Descent      0
Premis Cd         0
Weapon Used Cd    0
Status            0
Status Desc       0
Crm Cd 2          0
Crm Cd 3          0
Crm Cd 4          0
LOCATION          0
LAT               0
LON               0
dtype: int64

# 5.Preparado datos

## Categorias a usar
vamos a terminar de definir cuales van a ser las variables predictorias

### Variables Categoricas
de las siguientes variables categoricas:``Date Rptd``, ``DATE OCC``, ``AREA NAME``, ``Vict Sex``, ``Vict Descent``, ``Status``, ``LOCATION``, ``Status Desc``:
prescindiremos de
* **Date Rptd:** indica cuando se denunció o informó.
* **AREA NAME:** descripcion del area/barrio al tener el mismo campo codificado(``AREA``) este deja de ser importante.
* **Status:** revela la misma informacion que ``Status Desc`` pero representado de distinta manera.

In [25]:
df= df.drop(columns=["AREA NAME", "Status", "Date Rptd"])

### Variables Númericas
de las siguientes variables númericas:``DR_NO``, ``TIME OCC``, ``AREA``, ``Rpt Dist No``, ``Part 1-2``, ``Crm Cd``, ``Vict Age``, ``Premis Cd``, ``Weapon Used Cd``, ``Crm Cd 2``, ``Crm Cd 3``, ``Crm Cd 4``, ``LAT``, ``LON``:
prescindiremos de
* **DR_NO:** es un simple identificador.
* **LAT:** descripcion demasiado precisa, es parte de una coordenada.
* **LON:** descripcion demasiado precisa, es parte de una coordenada.

In [26]:
df=df.drop(columns=["DR_NO", "LAT", "LON"])

#adecuando tipos numericas
df["Premis Cd"]=df["Premis Cd"].astype(int)
df["Weapon Used Cd"]=df["Weapon Used Cd"].astype(int)
df["Crm Cd 2"]=df["Crm Cd 2"].astype(int)
df["Crm Cd 3"]=df["Crm Cd 3"].astype(int)
df["Crm Cd 4"]=df["Crm Cd 4"].astype(int)

de esta manera nos quedan los siguientes campos:
* **informacion Crimen**:
  -  **Cuando:** ``DATE OCC``, ``TIME OCC``
  -  **Donde:** ``AREA``(Barrio), ``Rpt Dist No``(Nº sector de barrio), ``LOCATION``(calle), ``Premis Cd``(descripcion de lugar)
  -  **Que:** ``Crm Cd``, ``Crm Cd 2``, ``Crm Cd 3``, ``Crm Cd 4``
  -  **Otra Info:** ``Part 1-2``(Nivel importancia de delito), ``Weapon Used Cd``(Cod de arma usada), ``Status Desc``(variable objetivo|arrestado/no arrestado)

* **informacion de Victima**
  - ``Vict Age``(edad de la victima)
  - ``Vict Sex``(sexo de la victima)
  - ``Vict Descent``(descendiencia/etnia de la victima)

In [27]:
df.info()

<class 'pandas.DataFrame'>
Index: 151337 entries, 0 to 757119
Data columns (total 16 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   DATE OCC        151337 non-null  str
 1   TIME OCC        151337 non-null  int64
 2   AREA            151337 non-null  int64
 3   Rpt Dist No     151337 non-null  int64
 4   Part 1-2        151337 non-null  int64
 5   Crm Cd          151337 non-null  int64
 6   Vict Age        151337 non-null  int64
 7   Vict Sex        151337 non-null  str
 8   Vict Descent    151337 non-null  str
 9   Premis Cd       151337 non-null  int64
 10  Weapon Used Cd  151337 non-null  int64
 11  Status Desc     151337 non-null  str
 12  Crm Cd 2        151337 non-null  int64
 13  Crm Cd 3        151337 non-null  int64
 14  Crm Cd 4        151337 non-null  int64
 15  LOCATION        151337 non-null  str
dtypes: int64(11), str(5)
memory usage: 19.6 MB

In [28]:
df.describe()

,TIME OCC,AREA,Rpt Dist No,Part 1-2,Crm Cd,Vict Age,Premis Cd,Weapon Used Cd,Crm Cd 2,Crm Cd 3,Crm Cd 4
count,151337.000000,151337.000000,151337.000000,151337.000000,151337.000000,151337.000000,151337.000000,151337.000000,151337.000000,151337.000000,151337.000000
mean,1339.527650,11.039495,1149.898234,1.591957,562.129136,32.437137,353.731077,410.545551,161.216596,8.416679,0.249800
std,655.812164,6.133926,613.596811,0.491473,244.496104,19.562811,204.076308,110.562116,361.494838,90.865951,15.763782
min,1.000000,1.000000,101.000000,1.000000,110.000000,-2.000000,101.000000,101.000000,0.000000,0.000000,0.000000
25%,900.000000,6.000000,625.000000,1.000000,310.000000,21.000000,108.000000,400.000000,0.000000,0.000000,0.000000
50%,1415.000000,11.000000,1162.000000,2.000000,624.000000,32.000000,501.000000,400.000000,0.000000,0.000000,0.000000
75%,1900.000000,16.000000,1675.000000,2.000000,740.000000,45.000000,502.000000,500.000000,0.000000,0.000000,0.000000
max,2359.000000,21.000000,2198.000000,2.000000,956.000000,99.000000,973.000000,516.000000,999.000000,999.000000,998.000000

In [29]:
df.shape

(151337, 16)

# Exportacion
Exportamos el dataset limpio.

In [30]:
df.to_csv("..\\data\\crimeData_subconjunto_not_invest.csv")