# CRIMES ANALYSIS
En este notebook se va a documentar los procesos necesarios al dataset

# 1. Importe de librerias

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import kagglehub
from kagglehub import KaggleDatasetAdapter
# Configuración básica
plt.rcParams['figure.figsize'] = (8,5)
print('Librerías cargadas correctamente')

Librerías cargadas correctamente

c:\Users\errec\Documents\Python B1\Runojanh-NadieEscapa\venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

# 2. Carga del Dataset

In [10]:
#Creacion de subconjuntos
# ruta = "..\\data\\Crime_Data_from_2020_to_Present.csv"
# df = pd.read_csv(ruta)
# df_filtrado_no_investigados = df[df['Status Desc'] != 'Invest Cont'].copy()
# df_filtrado_no_investigados.to_csv('..\\data\\Dataset_crimes_not_invest.csv', index=False)
# df_filtrado_investigados = df[df['Status Desc'] == 'Invest Cont'].copy()
# df_filtrado_investigados.to_csv('..\\data\\Dataset_crimes_invest.csv', index=False)

ruta = "..\\data\\Dataset_crimes_not_invest.csv"
df = pd.read_csv(ruta)
df.head()

,DR_NO,Date Rptd,DATE OCC,TIME OCC,AREA,AREA NAME,Rpt Dist No,Part 1-2,Crm Cd,Crm Cd Desc,...,Status,Status Desc,Crm Cd 1,Crm Cd 2,Crm Cd 3,Crm Cd 4,LOCATION,Cross Street,LAT,LON
0,10304468,01/08/2020 12:00:00 AM,01/08/2020 12:00:00 AM,2230,3,Southwest,377,2,624,BATTERY - SIMPLE ASSAULT,...,AO,Adult Other,624.0,NaN,NaN,NaN,1100 W 39TH PL,NaN,34.0141,-118.2978
1,200110444,04/14/2020 12:00:00 AM,02/13/2020 12:00:00 AM,1200,1,Central,155,2,845,SEX OFFENDER REGISTRANT OUT OF COMPLIANCE,...,AA,Adult Arrest,845.0,NaN,NaN,NaN,200 E 6TH ST,NaN,34.0448,-118.2474
2,201710201,06/19/2020 12:00:00 AM,05/26/2020 12:00:00 AM,1925,17,Devonshire,1708,1,341,"THEFT-GRAND ($950.01 & OVER)EXCPT,GUNS,FOWL,LI...",...,AO,Adult Other,341.0,NaN,NaN,NaN,11900 BALBOA BL,NaN,34.2864,-118.5021
3,200100514,01/05/2020 12:00:00 AM,01/05/2020 12:00:00 AM,1355,1,Central,162,1,341,"THEFT-GRAND ($950.01 & OVER)EXCPT,GUNS,FOWL,LI...",...,AA,Adult Arrest,341.0,NaN,NaN,NaN,800 S OLIVE ST,NaN,34.0452,-118.2569
4,201116159,11/29/2020 12:00:00 AM,11/28/2020 12:00:00 AM,2018,11,Northeast,1124,2,626,INTIMATE PARTNER - SIMPLE ASSAULT,...,AO,Adult Other,626.0,NaN,NaN,NaN,3200 W AVENUE 32,NaN,34.1186,-118.2450

# 3. Exploracion

### tamaño de Dataset

In [11]:
df.shape

(151340, 28)

### informacion del dataset

In [12]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 151340 entries, 0 to 151339
Data columns (total 28 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   DR_NO           151340 non-null  int64
 1   Date Rptd       151340 non-null  str
 2   DATE OCC        151340 non-null  str
 3   TIME OCC        151340 non-null  int64
 4   AREA            151340 non-null  int64
 5   AREA NAME       151340 non-null  str
 6   Rpt Dist No     151340 non-null  int64
 7   Part 1-2        151340 non-null  int64
 8   Crm Cd          151340 non-null  int64
 9   Crm Cd Desc     151340 non-null  str
 10  Mocodes         144702 non-null  str
 11  Vict Age        151340 non-null  int64
 12  Vict Sex        145452 non-null  str
 13  Vict Descent    145449 non-null  str
 14  Premis Cd       151340 non-null  float64
 15  Premis Desc     151248 non-null  str
 16  Weapon Used Cd  104089 non-null  float64
 17  Weapon Desc     104089 non-null  str
 18  Status          151340 non-null  str
 19  Status Desc     151340 non-null  str
 20  Crm Cd 1        151340 non-null  float64
 21  Crm Cd 2        25389 non-null   float64
 22  Crm Cd 3        1290 non-null    float64
 23  Crm Cd 4        38 non-null      float64
 24  LOCATION        151340 non-null  str
 25  Cross Street    22953 non-null   str
 26  LAT             151340 non-null  float64
 27  LON             151340 non-null  float64
dtypes: float64(8), int64(7), str(13)
memory usage: 32.3 MB

### descripcion detallada de Dataset

In [13]:
df.describe()

,DR_NO,TIME OCC,AREA,Rpt Dist No,Part 1-2,Crm Cd,Vict Age,Premis Cd,Weapon Used Cd,Crm Cd 1,Crm Cd 2,Crm Cd 3,Crm Cd 4,LAT,LON
count,1.513400e+05,151340.000000,151340.000000,151340.000000,151340.000000,151340.000000,151340.000000,151340.00000,104089.000000,151340.000000,25389.000000,1290.000000,38.000000,151340.000000,151340.000000
mean,2.129860e+08,1339.530633,11.039375,1149.885979,1.591952,562.128591,32.437029,353.73356,369.935670,561.497264,960.993344,987.406977,994.842105,34.080355,-118.354952
std,9.889679e+06,655.806202,6.133976,613.602194,0.491474,244.495347,19.562833,204.07941,111.767515,244.187471,101.813564,44.305076,13.704460,0.275578,0.867323
min,1.030447e+07,1.000000,1.000000,101.000000,1.000000,110.000000,-2.000000,101.00000,101.000000,110.000000,210.000000,434.000000,930.000000,0.000000,-118.667300
25%,2.018093e+08,900.000000,6.000000,625.000000,1.000000,310.000000,21.000000,108.00000,400.000000,310.000000,998.000000,998.000000,998.000000,34.016800,-118.442100
50%,2.114144e+08,1415.000000,11.000000,1162.000000,2.000000,624.000000,32.000000,501.00000,400.000000,624.000000,998.000000,998.000000,998.000000,34.066300,-118.327700
75%,2.211083e+08,1900.000000,16.000000,1675.000000,2.000000,740.000000,45.000000,502.00000,400.000000,740.000000,998.000000,998.000000,998.000000,34.186700,-118.278300
max,2.399090e+08,2359.000000,21.000000,2198.000000,2.000000,956.000000,99.000000,973.00000,516.000000,956.000000,999.000000,999.000000,998.000000,34.334300,0.000000

# 4.Filtro de datos
Categorias a usar

0   DR_NO           757141 non-null  int64  
 1   Date Rptd       757141 non-null  str    
 2   DATE OCC        757141 non-null  str    
 3   TIME OCC        757141 non-null  int64  
 4   AREA            757141 non-null  int64  
 5   AREA NAME       757141 non-null  str    
 6   Rpt Dist No     757141 non-null  int64  
 7   Part 1-2        757141 non-null  int64  
 8   Crm Cd          757141 non-null  int64  
 9   Crm Cd Desc     757141 non-null  str    
 10  Mocodes         653226 non-null  str    
 11  Vict Age        757141 non-null  int64  
 12  Vict Sex        658230 non-null  str    
 13  Vict Descent    658224 non-null  str    
 14  Premis Cd       757132 non-null  float64
 15  Premis Desc     756699 non-null  str    
 16  Weapon Used Cd  263079 non-null  float64
 17  Weapon Desc     263079 non-null  str    
 18  Status          757141 non-null  str    
 19  Status Desc     757141 non-null  str    
 20  Crm Cd 1        757131 non-null  float64
 21  Crm Cd 2        56016 non-null   float64
 22  Crm Cd 3        1872 non-null    float64
 23  Crm Cd 4        56 non-null      float64
 24  LOCATION        757141 non-null  str    
 25  Cross Street    121732 non-null  str    
 26  LAT             757141 non-null  float64
 27  LON             757141 non-null  float64

In [ ]:
ColumnasAUsar=df[["DR_NO", "TIME OCC", "DATE OCC", "AREA NAME", "Crm Cd Desc","Crm Cd 2","Crm Cd 3","Crm Cd 4", "Vict Age", "Vict Sex", "Vict Descent","Premis Desc", "Weapon Desc", "Status Desc", "Part 1-2","LOCATION"]]