# DOCUMENTACION INPUTS PARA PREDICCION

In [ ]:
import joblib
from sklearn.preprocessing import LabelEncoder
import pandas as pd

>**En este notebook se va a registrar la informacion necesaria para que el usuario pueda introducir los datos de un caso a predecir, es decir, los inputs de forma correcta para poder aprovechar el modelo predictivo al cien por cien**

**para empezar se usaran las siguientes variables:**

- **DATE OCC :** Fecha en la que sucedio el crimen.
- **TIME OCC :** Hora en la que sucedio el crimen.
- **AREA NAME :** Nombre del barrio.
- **Rpt Dist No :** Numero del sector de barrio
- **Part 1-2 :** Nivel de importancia de crimen principal
- **Crm Cd Desc:** Descripcion del crimen principal
- **Crm Cd 2 Desc:** Descripcion de crimen secundario
- **Crm Cd 3 Desc:** Descripcion de crimen secundario
- **Crm Cd 4 Desc:** Descripcion de crimen secundario
- **Vict Age :** Edad de la victima
- **Vict Sex :** Sexo de la víctima
- **Vict Descent :** Descendencia de la víctima
- **Premis Desc :** Descripción del lugar en el cual ocurrió el crimen
- **Weapon Desc :** Descripción del arma usada

## Variables Numericas:

- **DATE OCC:** Se debera escribir en formato Mes/Dia/Año
- **TIME OCC:** Se deberá escribir en formato militar 12:30 -> 1230
- **Rpt Dist No :** Se deberá escribir un valor numérico comprendido en el rango 101-2198 ambos incluidos
- **Part 1-2 :** Facil sencillo y para toda la familia, dos posibles valores: 1 o 2
- **Vict Age :** Se deberá escribir un valor comprendido en el rango 0-99 ambos incluidos, es un intervalo bastante amplio por lo tanto no creo que haya problemas con esta regla.

## Variables Categóricas:

### Crimenes
Tanto para el crimen Principal como los secundarios se escribirá exactamente cualquiera de los 129 valores.

In [14]:
df=pd.read_csv("../models/mapper_crm.csv")
serieTiposCasos=df[["Crm Cd Desc"]]
serieTiposCasos

                                           Crm Cd Desc
0                             BATTERY - SIMPLE ASSAULT
1            SEX OFFENDER REGISTRANT OUT OF COMPLIANCE
2             VANDALISM - MISDEAMEANOR ($399 OR UNDER)
3    VANDALISM - FELONY ($400 & OVER, ALL CHURCH VA...
4                                       RAPE, FORCIBLE
..                                                 ...
124  BEASTIALITY, CRIME AGAINST NATURE SEXUAL ASSLT...
125                                             BIGAMY
126  FIREARMS EMERGENCY PROTECTIVE ORDER (FIREARMS ...
127       INCEST (SEXUAL ACTS BETWEEN BLOOD RELATIVES)
128                     BLOCKING DOOR INDUCTION CENTER

[129 rows x 1 columns]

### Vict Sex
valor categórico, F:Femenino(Female), M:Masculino(Male), X:Desconocido

### Vict Descent
- **A :** Otras personas asiáticas
- **B :** Personas negras
- **C :** Personas chinas
- **D :** Personas camboyanas
- **F :** Personas filipinas
- **G :** Personas guameñas
- **H :** Personas hispanas / latinoamericanas / mexicanas
- **I :** Personas indígenas americanas / nativas de Alaska
- **J :** Personas japonesas
- **K :** Personas coreanas
- **O :** Otras
- **P :** Personas de islas del Pacífico
- **S :** Personas samoanas
- **U :** Hawaianos
- **V :** Vietnamitas
- **W :** Personas blancas
- **X :** Desconocido
- **Z :** Asiáticos indios

In [9]:
encoder :LabelEncoder = joblib.load("../models/encoder_VictDescent.joblib")
encoder.classes_

array(['A', 'B', 'C', 'D', 'F', 'G', 'H', 'I', 'J', 'K', 'O', 'P', 'S',
       'U', 'V', 'W', 'X', 'Z'], dtype=object)

### AREA NAME
se escribirá exactamente cualquiera de los 20 valores.

In [17]:
df=pd.read_csv("../models/mapper_area.csv")
serieTiposArea=df[["AREA NAME"]]
serieTiposArea

      AREA NAME
0     Southwest
1       Central
2   N Hollywood
3       Mission
4    Devonshire
5     Northeast
6        Harbor
7      Van Nuys
8   West Valley
9       West LA
10     Wilshire
11      Pacific
12      Rampart
13  77th Street
14   Hollenbeck
15    Southeast
16    Hollywood
17       Newton
18      Topanga
19     Foothill
20      Olympic

### Premis Desc
se escribirá exactamente cualquiera de los 20 valores.

In [18]:
df=pd.read_csv("../models/mapper_premis.csv")
serieTiposPremis=df[["Premis Desc"]]
serieTiposPremis

                                        Premis Desc
0                            SINGLE FAMILY DWELLING
1                                          SIDEWALK
2                                   POLICE FACILITY
3      MULTI-UNIT DWELLING (APARTMENT, DUPLEX, ETC)
4                               BEAUTY SUPPLY STORE
..                                              ...
273                     MTA - ORANGE LINE - DE SOTO
274  TRAIN, OTHER THAN MTA (ALSO QUERY 809/810/811)
275         HARBOR FRWY STATION (NOT LINE SPECIFIC)
276                                             NaN
277                                             NaN

[278 rows x 1 columns]

### Weapon Desc
se escribirá exactamente cualquiera de los 20 valores.

In [ ]:
df=pd.read_csv("../models/mapper_weapon.csv")
serieTiposWeapon=df[["Weapon Desc"]]
serieTiposWeapon

                                       Weapon Desc
0   STRONG-ARM (HANDS, FIST, FEET OR BODILY FORCE)
1                      UNKNOWN WEAPON/OTHER WEAPON
2                               ROCK/THROWN OBJECT
3                                    VERBAL THREAT
4                                    FOLDING KNIFE
..                                             ...
70                                  STRAIGHT RAZOR
71                                       BLACKJACK
72                                   RELIC FIREARM
73   HECKLER & KOCH 91 SEMIAUTOMATIC ASSAULT RIFLE
74            UNK TYPE SEMIAUTOMATIC ASSAULT RIFLE

[75 rows x 1 columns]