# 🧠 Clasificación con Machine Learning (Titanic)

Aprenderás a entrenar y entender paso a paso varios modelos de clasificación.

## 📦 Importación de librerías

In [15]:

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from catboost import CatBoostClassifier, Pool

## 📊 Cargar datos

In [10]:

df = pd.read_csv("..\\data\\crimeData_subconjunto.csv")
df =df.drop(columns="Unnamed: 0")
# df_test = pd.read_csv("cure_the_princess\\test.csv")
df.head()

,AREA NAME,Part 1-2,Vict Age,Vict Sex,Vict Descent,Premis Desc,Weapon Desc,Status Desc,Crm Cd Desc,Crm Cd 2,Crm Cd 3,Crm Cd 4,DATE OCC,TIME OCC
0,Southwest,2,36,F,B,SINGLE FAMILY DWELLING,"STRONG-ARM (HANDS, FIST, FEET OR BODILY FORCE)",no_arrest,BATTERY - SIMPLE ASSAULT,0.0,0.0,0.0,01/08/2020 12:00:00 AM,2230
1,Central,2,0,X,X,POLICE FACILITY,UNKNOWN WEAPON/OTHER WEAPON,arrest,SEX OFFENDER REGISTRANT OUT OF COMPLIANCE,0.0,0.0,0.0,02/13/2020 12:00:00 AM,1200
2,Devonshire,1,0,X,X,OTHER BUSINESS,UNKNOWN WEAPON/OTHER WEAPON,no_arrest,"THEFT-GRAND ($950.01 & OVER)EXCPT,GUNS,FOWL,LI...",0.0,0.0,0.0,05/26/2020 12:00:00 AM,1925
3,Central,1,41,M,A,HOTEL,UNKNOWN WEAPON/OTHER WEAPON,arrest,"THEFT-GRAND ($950.01 & OVER)EXCPT,GUNS,FOWL,LI...",0.0,0.0,0.0,01/05/2020 12:00:00 AM,1355
4,Northeast,2,34,F,H,SINGLE FAMILY DWELLING,"STRONG-ARM (HANDS, FIST, FEET OR BODILY FORCE)",no_arrest,INTIMATE PARTNER - SIMPLE ASSAULT,0.0,0.0,0.0,11/28/2020 12:00:00 AM,2018

In [5]:
df.describe()

,Unnamed: 0,Phoenix Feather,Unicorn Horn,Dragon's Blood,Mermaid Tears,Fairy Dust,Goblin Toes,Witch's Brew,Griffin Claw,Troll Hair,Kraken Ink,Minotaur Horn,Basilisk Scale,Chimera Fang,Cured
count,1870.000000,1870.000000,1870.000000,1870.000000,1870.000000,1870.000000,1870.000000,1870.000000,1870.000000,1870.000000,1870.000000,1870.000000,1870.000000,1870.000000,1870.000000
mean,1175.873262,15.470963,10.869840,16.145241,13.750481,15.077540,14.166364,12.289305,14.769412,17.043422,14.916150,10.922353,15.390695,12.217326,0.494118
std,672.929407,8.721213,7.297803,8.363038,7.631516,8.301043,7.895467,7.687816,8.078848,9.598987,8.009475,7.044564,8.657294,8.148566,0.500099
min,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000
25%,604.500000,8.500000,5.100000,9.600000,7.600000,8.800000,7.800000,6.400000,8.300000,9.125000,8.800000,5.200000,8.700000,5.500000,0.000000
50%,1180.500000,14.800000,9.300000,15.900000,13.100000,14.500000,13.500000,11.100000,14.300000,16.500000,14.500000,9.600000,14.800000,10.700000,0.000000
75%,1744.750000,21.700000,15.500000,22.075000,19.200000,20.775000,19.675000,16.700000,20.400000,24.200000,20.500000,15.275000,21.100000,17.500000,1.000000
max,2337.000000,42.100000,34.100000,40.800000,34.100000,40.000000,37.800000,37.300000,39.400000,44.800000,39.500000,33.700000,42.000000,37.600000,1.000000

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 151337 entries, 0 to 151336
Data columns (total 14 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   AREA NAME     151337 non-null  str
 1   Part 1-2      151337 non-null  int64
 2   Vict Age      151337 non-null  int64
 3   Vict Sex      151337 non-null  str
 4   Vict Descent  151337 non-null  str
 5   Premis Desc   151337 non-null  str
 6   Weapon Desc   151337 non-null  str
 7   Status Desc   151337 non-null  str
 8   Crm Cd Desc   151337 non-null  str
 9   Crm Cd 2      151337 non-null  float64
 10  Crm Cd 3      151337 non-null  float64
 11  Crm Cd 4      151337 non-null  float64
 12  DATE OCC      151337 non-null  str
 13  TIME OCC      151337 non-null  int64
dtypes: float64(3), int64(3), str(8)
memory usage: 16.2 MB

In [3]:
df.shape

(151337, 13)

In [11]:
df.isnull().sum()

AREA NAME       0
Part 1-2        0
Vict Age        0
Vict Sex        0
Vict Descent    0
Premis Desc     0
Weapon Desc     0
Status Desc     0
Crm Cd Desc     0
Crm Cd 2        0
Crm Cd 3        0
Crm Cd 4        0
DATE OCC        0
TIME OCC        0
dtype: int64

## 🧹 Limpieza


## 🔍 ¿Por qué dividir en Train y Test?

En Machine Learning no evaluamos el modelo con los mismos datos con los que lo entrenamos.

- **Train (entrenamiento):** el modelo aprende patrones
- **Test (evaluación):** comprobamos si generaliza bien a datos nuevos

👉 Si no hacemos esta separación, el modelo puede parecer muy bueno pero fallar en la realidad (overfitting)

In [14]:

# Ejemplo conceptual sencillo

from sklearn.model_selection import train_test_split
# df.fillna(0)
 
# Creamos datos de ejemplo
X = df.drop(columns=["Status Desc"])
y = df["Status Desc"]
 
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

print("Train size:", X_train.shape)
print("Test size:", X_test.shape)

Train size: (121069, 13)
Test size: (30268, 13)

In [7]:
X.columns

Index(['AREA NAME', 'Part 1-2', 'Vict Age', 'Vict Sex', 'Vict Descent',
       'Premis Desc', 'Weapon Desc', 'Crm Cd Desc', 'Crm Cd 2', 'Crm Cd 3',
       'Crm Cd 4', 'DATE OCC', 'TIME OCC'],
      dtype='str')

## 🔀 División train/test

In [ ]:

# X = df.drop('survived', axis=1)
# y = df['survived']

# X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [ ]:
# X_train = df[["Witch's Brew", "Troll Hair", "Kraken Ink", "Basilisk Scale"]]
# y_train = df['Cured']
# X_test = df_test[["Witch's Brew", "Troll Hair", "Kraken Ink", "Basilisk Scale"]]
# y_test = df_test['Cured']

## ⚖️ Escalado

In [ ]:

# scaler = StandardScaler()
# X_train = scaler.fit_transform(X_train)
# X_test = scaler.transform(X_test)

# Entrenamiento de modelos


## 🔵 Regresión Logística

### Explicación del código:
- `LogisticRegression()` crea el modelo
- `.fit(X_train, y_train)` entrena el modelo con los datos
- `.predict(X_test)` hace predicciones
- `accuracy_score` mide el rendimiento

In [39]:

model = LogisticRegression()

# Entrenamos el modelo
model.fit(X_train, y_train)

# Predecimos
preds = model.predict(X_test)
print(X_test.shape)
print(y_test.shape, preds.shape)
# Evaluamos
print("Accuracy:", accuracy_score(y_test, preds))

(30268, 31)
(30268,) (30268,)
Accuracy: 0.6520747984670279

### CAT BOOST

In [17]:
# 0   AREA NAME     151337 non-null  str    
#  1   Part 1-2      151337 non-null  int64  
#  2   Vict Age      151337 non-null  int64  
#  3   Vict Sex      151337 non-null  str    
#  4   Vict Descent  151337 non-null  str    
#  5   Premis Desc   151337 non-null  str    
#  6   Weapon Desc   151337 non-null  str    
#  7   Status Desc   151337 non-null  str    
#  8   Crm Cd Desc   151337 non-null  str    
#  9   Crm Cd 2      151337 non-null  float64
#  10  Crm Cd 3      151337 non-null  float64
#  11  Crm Cd 4      151337 non-null  float64
#  12  DATE OCC      151337 non-null  str    
#  13  TIME OCC      151337 non-null  int64  
cat_cols = ["AREA NAME", "Vict Sex", "Vict Descent", "Premis Desc", "Weapon Desc", "Crm Cd Desc", "DATE OCC"]
 
# ─────────────────────────────────────────────
# 2. SPLIT
# ─────────────────────────────────────────────
 


cat_features_idx = [X.columns.get_loc(c) for c in cat_cols]
# → [0, 1, 2, 3, 4]
 
train_pool = Pool(X_train, y_train, cat_features=cat_features_idx)
test_pool  = Pool(X_test,  y_test,  cat_features=cat_features_idx)
 
model = CatBoostClassifier(
    iterations=500,
    learning_rate=0.05,
    depth=6,
    loss_function="Logloss",
    eval_metric="Accuracy",
    random_seed=42,
    verbose=100,           # imprime cada 100 iteraciones
)
model.fit(train_pool, eval_set=test_pool, early_stopping_rounds=50)
y_pred = model.predict(X_test)

print(classification_report(y_test, y_pred))
# precision, recall, f1-score por clase

print(confusion_matrix(y_test, y_pred))

0:	learn: 0.6729468	test: 0.6772499	best: 0.6772499 (0)	total: 246ms	remaining: 2m 2s
100:	learn: 0.6917378	test: 0.7014008	best: 0.7014008 (100)	total: 12.4s	remaining: 49s
200:	learn: 0.6972718	test: 0.7082728	best: 0.7085701 (199)	total: 25.3s	remaining: 37.6s
300:	learn: 0.6999067	test: 0.7102220	best: 0.7105524 (265)	total: 38s	remaining: 25.1s
Stopped by overfitting detector  (50 iterations wait)

bestTest = 0.7105523986
bestIteration = 265

Shrink model to first 266 iterations.
              precision    recall  f1-score   support

      arrest       0.71      0.62      0.66     13724
   no_arrest       0.71      0.79      0.75     16544

    accuracy                           0.71     30268
   macro avg       0.71      0.70      0.70     30268
weighted avg       0.71      0.71      0.71     30268

[[ 8443  5281]
 [ 3480 13064]]


## 🟢 KNN

### Explicación del código:
- `n_neighbors=5` → usa los 5 vecinos más cercanos
- El modelo NO aprende una fórmula → guarda los datos
- Para predecir: busca los puntos más cercanos

In [40]:

model = KNeighborsClassifier(n_neighbors=5)

model.fit(X_train, y_train)

preds = model.predict(X_test)

print("Accuracy:", accuracy_score(y_test, preds))

Accuracy: 0.6349279767411127


## 🌳 Árbol de decisión

### Explicación del código:
- `max_depth=4` limita la profundidad del árbol
- El modelo crea reglas tipo:
  "si edad < 30 → ..."
- Más profundidad = más complejidad (riesgo de overfitting)

In [41]:

model = DecisionTreeClassifier(max_depth=4)

model.fit(X_train, y_train)

preds = model.predict(X_test)

print("Accuracy:", accuracy_score(y_test, preds))

Accuracy: 0.6627791727236686


## 🌲 Random Forest

### Explicación del código:
- `n_estimators=100` → número de árboles
- Cada árbol aprende algo distinto
- El resultado final es la media/votación de todos

In [42]:

model = RandomForestClassifier(n_estimators=50)

model.fit(X_train, y_train)

preds = model.predict(X_test)

print("Accuracy:", accuracy_score(y_test, preds))

Accuracy: 0.6542883573410863


## ⚫ SVM

### Explicación del código:
- Busca la mejor frontera de separación entre clases
- Usa hiperplanos (líneas en 2D)
- Muy potente en datasets complejos

In [ ]:

model = SVC()

model.fit(X_train, y_train)

preds = model.predict(X_test)

print("Accuracy:", accuracy_score(y_test, preds))