# 🧠 Clasificación con Machine Learning (Titanic)

Aprenderás a entrenar y entender paso a paso varios modelos de clasificación.

## 📦 Importación de librerías

In [1]:

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, classification_report

from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC

## 📊 Cargar datos

In [2]:

df = pd.read_csv("..\\data\\crimeData_subconjunto_no_invest.csv")
df =df.drop(columns="Unnamed: 0")
# df_test = pd.read_csv("cure_the_princess\\test.csv")
df.head()

,TIME OCC,AREA,Rpt Dist No,Part 1-2,Crm Cd,Vict Age,Vict Sex,Vict Descent,Premis Cd,Weapon Used Cd,Status Desc,Crm Cd 2,Crm Cd 3,Crm Cd 4,LOCATION,YEAR OCC,MONTH OCC,DAY OCC
0,2230,3,377,2,624,36,0,0,501,400,1.0,0,0,0,0,2020,1,8
1,1200,1,155,2,845,0,2,2,726,500,2.0,0,0,0,2,2020,2,13
2,1925,17,1708,1,341,0,2,2,203,500,1.0,0,0,0,8,2020,5,26
3,1355,1,162,1,341,41,1,4,503,500,2.0,0,0,0,11,2020,1,5
4,2018,11,1124,2,626,34,0,1,501,400,1.0,0,0,0,15,2020,11,28

In [5]:
df.describe()

,Unnamed: 0,Phoenix Feather,Unicorn Horn,Dragon's Blood,Mermaid Tears,Fairy Dust,Goblin Toes,Witch's Brew,Griffin Claw,Troll Hair,Kraken Ink,Minotaur Horn,Basilisk Scale,Chimera Fang,Cured
count,1870.000000,1870.000000,1870.000000,1870.000000,1870.000000,1870.000000,1870.000000,1870.000000,1870.000000,1870.000000,1870.000000,1870.000000,1870.000000,1870.000000,1870.000000
mean,1175.873262,15.470963,10.869840,16.145241,13.750481,15.077540,14.166364,12.289305,14.769412,17.043422,14.916150,10.922353,15.390695,12.217326,0.494118
std,672.929407,8.721213,7.297803,8.363038,7.631516,8.301043,7.895467,7.687816,8.078848,9.598987,8.009475,7.044564,8.657294,8.148566,0.500099
min,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000
25%,604.500000,8.500000,5.100000,9.600000,7.600000,8.800000,7.800000,6.400000,8.300000,9.125000,8.800000,5.200000,8.700000,5.500000,0.000000
50%,1180.500000,14.800000,9.300000,15.900000,13.100000,14.500000,13.500000,11.100000,14.300000,16.500000,14.500000,9.600000,14.800000,10.700000,0.000000
75%,1744.750000,21.700000,15.500000,22.075000,19.200000,20.775000,19.675000,16.700000,20.400000,24.200000,20.500000,15.275000,21.100000,17.500000,1.000000
max,2337.000000,42.100000,34.100000,40.800000,34.100000,40.000000,37.800000,37.300000,39.400000,44.800000,39.500000,33.700000,42.000000,37.600000,1.000000

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 151337 entries, 0 to 151336
Data columns (total 18 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   TIME OCC        151337 non-null  int64
 1   AREA            151337 non-null  int64
 2   Rpt Dist No     151337 non-null  int64
 3   Part 1-2        151337 non-null  int64
 4   Crm Cd          151337 non-null  int64
 5   Vict Age        151337 non-null  int64
 6   Vict Sex        151337 non-null  int64
 7   Vict Descent    151337 non-null  int64
 8   Premis Cd       151337 non-null  int64
 9   Weapon Used Cd  151337 non-null  int64
 10  Status Desc     151337 non-null  float64
 11  Crm Cd 2        151337 non-null  int64
 12  Crm Cd 3        151337 non-null  int64
 13  Crm Cd 4        151337 non-null  int64
 14  LOCATION        151337 non-null  int64
 15  YEAR OCC        151337 non-null  int64
 16  MONTH OCC       151337 non-null  int64
 17  DAY OCC         151337 non-null  int64
dtypes: float64(1), int64(17)
memory usage: 20.8 MB

In [3]:
df.shape

(151337, 13)

## 🧹 Limpieza


## 🔍 ¿Por qué dividir en Train y Test?

En Machine Learning no evaluamos el modelo con los mismos datos con los que lo entrenamos.

- **Train (entrenamiento):** el modelo aprende patrones
- **Test (evaluación):** comprobamos si generaliza bien a datos nuevos

👉 Si no hacemos esta separación, el modelo puede parecer muy bueno pero fallar en la realidad (overfitting)

In [3]:

# Ejemplo conceptual sencillo

from sklearn.model_selection import train_test_split
# df.fillna(0)
 
# Creamos datos de ejemplo
X = df.drop('Status Desc', axis=1)
y = df['Status Desc']

# Dividimos en 80% entrenamiento y 20% test
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

print("Train size:", X_train.shape)
print("Test size:", X_test.shape)

Train size: (121069, 17)
Test size: (30268, 17)

In [7]:
X.columns

Index(['TIME OCC', 'AREA', 'Rpt Dist No', 'Part 1-2', 'Crm Cd', 'Vict Age',
       'Vict Sex', 'Vict Descent', 'Premis Cd', 'Weapon Used Cd', 'Crm Cd 2',
       'Crm Cd 3', 'Crm Cd 4', 'LOCATION', 'YEAR OCC', 'MONTH OCC', 'DAY OCC'],
      dtype='str')

## 🔀 División train/test

In [ ]:

# X = df.drop('survived', axis=1)
# y = df['survived']

# X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [ ]:
# X_train = df[["Witch's Brew", "Troll Hair", "Kraken Ink", "Basilisk Scale"]]
# y_train = df['Cured']
# X_test = df_test[["Witch's Brew", "Troll Hair", "Kraken Ink", "Basilisk Scale"]]
# y_test = df_test['Cured']

## ⚖️ Escalado

In [4]:

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Entrenamiento de modelos


## 🔵 Regresión Logística

### Explicación del código:
- `LogisticRegression()` crea el modelo
- `.fit(X_train, y_train)` entrena el modelo con los datos
- `.predict(X_test)` hace predicciones
- `accuracy_score` mide el rendimiento

In [5]:

model = LogisticRegression()

# Entrenamos el modelo
model.fit(X_train, y_train)

# Predecimos
preds = model.predict(X_test)
print(X_test.shape)
print(y_test.shape, preds.shape)
# Evaluamos
print("Accuracy:", accuracy_score(y_test, preds))

(30268, 17)
(30268,) (30268,)
Accuracy: 0.6455662746134532


## 🟢 KNN

### Explicación del código:
- `n_neighbors=5` → usa los 5 vecinos más cercanos
- El modelo NO aprende una fórmula → guarda los datos
- Para predecir: busca los puntos más cercanos

In [6]:

model = KNeighborsClassifier(n_neighbors=5)

model.fit(X_train, y_train)

preds = model.predict(X_test)

print("Accuracy:", accuracy_score(y_test, preds))

Accuracy: 0.615270252411788


## 🌳 Árbol de decisión

### Explicación del código:
- `max_depth=4` limita la profundidad del árbol
- El modelo crea reglas tipo:
  "si edad < 30 → ..."
- Más profundidad = más complejidad (riesgo de overfitting)

In [7]:

model = DecisionTreeClassifier(max_depth=4)

model.fit(X_train, y_train)

preds = model.predict(X_test)

print("Accuracy:", accuracy_score(y_test, preds))

Accuracy: 0.6621844852649663


## 🌲 Random Forest

### Explicación del código:
- `n_estimators=100` → número de árboles
- Cada árbol aprende algo distinto
- El resultado final es la media/votación de todos

In [ ]:

model = RandomForestClassifier(n_estimators=50)

model.fit(X_train, y_train)

preds = model.predict(X_test)

# model DUMP

print("Accuracy:", accuracy_score(y_test, preds))

Accuracy: 0.6924144310823311


## ⚫ SVM

### Explicación del código:
- Busca la mejor frontera de separación entre clases
- Usa hiperplanos (líneas en 2D)
- Muy potente en datasets complejos

In [ ]:

model = SVC()

model.fit(X_train, y_train)

preds = model.predict(X_test)

print("Accuracy:", accuracy_score(y_test, preds))

Debido a que se ha creado el dataset codificado haciendo label encoding a variables con mucha cardinalidad la mejor opcion es el algoritmo de entrenamiento Random Forest y aparte que es la mejor puntuacion.